
import net.minecraft.block.material.*;
import net.minecraft.client.*;
import net.minecraft.client.audio.*;
import net.minecraft.client.entity.*;
import net.minecraft.client.gui.*;
import net.minecraft.client.gui.achievement.*;
import net.minecraft.client.gui.inventory.*;
import net.minecraft.client.model.*;
import net.minecraft.client.multiplayer.*;
import net.minecraft.client.particle.*;
import net.minecraft.client.renderer.*;
import net.minecraft.client.renderer.culling.*;
import net.minecraft.client.renderer.entity.*;
import net.minecraft.client.renderer.tileentity.*;
import net.minecraft.client.settings.*;
import net.minecraft.command.*;
import net.minecraft.crash.*;
import net.minecraft.creativetab.*;
import net.minecraft.dispenser.*;
import net.minecraft.enchantment.*;
import net.minecraft.entity.*;
import net.minecraft.entity.ai.*;
import net.minecraft.entity.boss.*;
import net.minecraft.entity.effect.*;
import net.minecraft.entity.item.*;
import net.minecraft.entity.monster.*;
import net.minecraft.entity.passive.*;
import net.minecraft.entity.player.*;
import net.minecraft.entity.projectile.*;
import net.minecraft.inventory.*;
import net.minecraft.item.*;
import net.minecraft.item.crafting.*;
import net.minecraft.nbt.*;
import net.minecraft.network.*;
import net.minecraft.network.rcon.*;
import net.minecraft.pathfinding.*;
import net.minecraft.potion.*;
import net.minecraft.profiler.*;
import net.minecraft.server.*;
import net.minecraft.server.dedicated.*;
import net.minecraft.server.gui.*;
import net.minecraft.server.integrated.*;
import net.minecraft.server.management.*;

import net.minecraft.stats.*;
import net.minecraft.tileentity.*;
import net.minecraft.util.*;
import net.minecraft.village.*;
import net.minecraft.world.*;
import net.minecraft.world.biome.*;
import net.minecraft.world.chunk.*;
import net.minecraft.world.chunk.storage.*;
import net.minecraft.world.demo.*;
import net.minecraft.world.gen.*;
import net.minecraft.world.gen.feature.*;
import net.minecraft.world.gen.layer.*;
import net.minecraft.world.gen.structure.*;
import net.minecraft.world.storage.*;
import net.minecraftforge.classloading.*;
import net.minecraftforge.client.*;
import net.minecraftforge.client.event.*;
import net.minecraftforge.client.event.sound.*;
import net.minecraftforge.common.*;
import net.minecraftforge.event.*;
import net.minecraftforge.event.entity.*;
import net.minecraftforge.event.entity.item.*;
import net.minecraftforge.event.entity.living.*;
import net.minecraftforge.event.entity.minecart.*;
import net.minecraftforge.event.entity.player.*;
import net.minecraftforge.event.terraingen.*;
import net.minecraftforge.event.world.*;
import net.minecraftforge.oredict.*;

import net.minecraftforge.fml.common.*;
import net.minecraftforge.fml.common.event.*;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.registry.*;
import net.minecraftforge.fml.common.network.*;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import java.util.Random;
import java.util.Map;
import net.minecraftforge.fml.relauncher.*;

public class ClientProxyTestEnvironmentMod extends CommonProxyTestEnvironmentMod{

	@Override
	public void registerRenderers(TestEnvironmentMod ins) {
		ins.mcreator_0.registerRenderers();
ins.mcreator_1.registerRenderers();
ins.mcreator_2.registerRenderers();
ins.mcreator_3.registerRenderers();
ins.mcreator_4.registerRenderers();
ins.mcreator_5.registerRenderers();
ins.mcreator_6.registerRenderers();
ins.mcreator_7.registerRenderers();
ins.mcreator_8.registerRenderers();
ins.mcreator_9.registerRenderers();
ins.mcreator_10.registerRenderers();
ins.mcreator_11.registerRenderers();
ins.mcreator_12.registerRenderers();
ins.mcreator_13.registerRenderers();
ins.mcreator_14.registerRenderers();
ins.mcreator_15.registerRenderers();
ins.mcreator_16.registerRenderers();
ins.mcreator_17.registerRenderers();
ins.mcreator_18.registerRenderers();
ins.mcreator_19.registerRenderers();
ins.mcreator_20.registerRenderers();
ins.mcreator_21.registerRenderers();
ins.mcreator_22.registerRenderers();
ins.mcreator_23.registerRenderers();
ins.mcreator_24.registerRenderers();
ins.mcreator_25.registerRenderers();
ins.mcreator_26.registerRenderers();
ins.mcreator_27.registerRenderers();
ins.mcreator_28.registerRenderers();
ins.mcreator_29.registerRenderers();
ins.mcreator_30.registerRenderers();
ins.mcreator_31.registerRenderers();
ins.mcreator_32.registerRenderers();
ins.mcreator_33.registerRenderers();
ins.mcreator_34.registerRenderers();
ins.mcreator_35.registerRenderers();
ins.mcreator_36.registerRenderers();
ins.mcreator_37.registerRenderers();
ins.mcreator_38.registerRenderers();
ins.mcreator_39.registerRenderers();
ins.mcreator_40.registerRenderers();
ins.mcreator_41.registerRenderers();
ins.mcreator_42.registerRenderers();
ins.mcreator_43.registerRenderers();
ins.mcreator_44.registerRenderers();
ins.mcreator_45.registerRenderers();

	}
}
