
import net.minecraft.block.material.*;
import net.minecraft.client.*;
import net.minecraft.client.audio.*;
import net.minecraft.client.entity.*;
import net.minecraft.client.gui.*;
import net.minecraft.client.gui.achievement.*;
import net.minecraft.client.gui.inventory.*;
import net.minecraft.client.model.*;
import net.minecraft.client.multiplayer.*;
import net.minecraft.client.particle.*;
import net.minecraft.client.renderer.*;
import net.minecraft.client.renderer.culling.*;
import net.minecraft.client.renderer.entity.*;
import net.minecraft.client.renderer.tileentity.*;
import net.minecraft.client.settings.*;
import net.minecraft.command.*;
import net.minecraft.crash.*;
import net.minecraft.creativetab.*;
import net.minecraft.dispenser.*;
import net.minecraft.enchantment.*;
import net.minecraft.entity.*;
import net.minecraft.entity.ai.*;
import net.minecraft.entity.boss.*;
import net.minecraft.entity.effect.*;
import net.minecraft.entity.item.*;
import net.minecraft.entity.monster.*;
import net.minecraft.entity.passive.*;
import net.minecraft.entity.player.*;
import net.minecraft.entity.projectile.*;
import net.minecraft.inventory.*;
import net.minecraft.item.*;
import net.minecraft.item.crafting.*;
import net.minecraft.nbt.*;
import net.minecraft.network.*;
import net.minecraft.network.rcon.*;
import net.minecraft.pathfinding.*;
import net.minecraft.potion.*;
import net.minecraft.profiler.*;
import net.minecraft.server.*;
import net.minecraft.server.dedicated.*;
import net.minecraft.server.gui.*;
import net.minecraft.server.integrated.*;
import net.minecraft.server.management.*;

import net.minecraft.stats.*;
import net.minecraft.tileentity.*;
import net.minecraft.util.*;
import net.minecraft.village.*;
import net.minecraft.world.*;
import net.minecraft.world.biome.*;
import net.minecraft.world.chunk.*;
import net.minecraft.world.chunk.storage.*;
import net.minecraft.world.demo.*;
import net.minecraft.world.gen.*;
import net.minecraft.world.gen.feature.*;
import net.minecraft.world.gen.layer.*;
import net.minecraft.world.gen.structure.*;
import net.minecraft.world.storage.*;
import net.minecraftforge.classloading.*;
import net.minecraftforge.client.*;
import net.minecraftforge.client.event.*;
import net.minecraftforge.client.event.sound.*;
import net.minecraftforge.common.*;
import net.minecraftforge.event.*;
import net.minecraftforge.event.entity.*;
import net.minecraftforge.event.entity.item.*;
import net.minecraftforge.event.entity.living.*;
import net.minecraftforge.event.entity.minecart.*;
import net.minecraftforge.event.entity.player.*;
import net.minecraftforge.event.terraingen.*;
import net.minecraftforge.event.world.*;
import net.minecraftforge.oredict.*;

import net.minecraftforge.fml.common.*;
import net.minecraftforge.fml.common.event.*;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.registry.*;
import net.minecraftforge.fml.common.network.*;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import java.util.*;
import io.netty.buffer.ByteBuf;

import net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec;
import io.netty.buffer.ByteBuf;
import io.netty.channel.ChannelHandlerContext;
import net.minecraftforge.fml.relauncher.*;

import net.minecraftforge.client.model.obj.*;

@Mod(modid = TestEnvironmentMod.MODID, version = TestEnvironmentMod.VERSION)
public class TestEnvironmentMod implements IFuelHandler, IWorldGenerator{

	public static final String MODID = "TestEnvironmentMod";
    public static final String VERSION = "1.0";

	@SidedProxy(clientSide="mod.mcreator.ClientProxyTestEnvironmentMod", serverSide="mod.mcreator.CommonProxyTestEnvironmentMod")
    public static CommonProxyTestEnvironmentMod proxy;

	@Instance(MODID)
    public static TestEnvironmentMod instance;

	mcreator_beachPalm mcreator_0 = new mcreator_beachPalm();
mcreator_seaWeedItem mcreator_1 = new mcreator_seaWeedItem();
mcreator_yellowRecord mcreator_2 = new mcreator_yellowRecord();
mcreator_tabDefqon1 mcreator_3 = new mcreator_tabDefqon1();
mcreator_wreckedShipBack mcreator_4 = new mcreator_wreckedShipBack();
mcreator_virginRecord mcreator_5 = new mcreator_virginRecord();
mcreator_blueRecord mcreator_6 = new mcreator_blueRecord();
mcreator_redRecord mcreator_7 = new mcreator_redRecord();
mcreator_genSeaWeeds mcreator_8 = new mcreator_genSeaWeeds();
mcreator_weedPlant mcreator_9 = new mcreator_weedPlant();
mcreator_magentaRecord mcreator_10 = new mcreator_magentaRecord();
mcreator_blackRecord mcreator_11 = new mcreator_blackRecord();
mcreator_goldRecord mcreator_12 = new mcreator_goldRecord();
mcreator_whiteRecord mcreator_13 = new mcreator_whiteRecord();
mcreator_brownRecord mcreator_14 = new mcreator_brownRecord();
mcreator_shapelessRedRecord mcreator_15 = new mcreator_shapelessRedRecord();
mcreator_uvRecord mcreator_16 = new mcreator_uvRecord();
mcreator_purpleRecord mcreator_17 = new mcreator_purpleRecord();
mcreator_silverRecord mcreator_18 = new mcreator_silverRecord();
mcreator_shapelessBlackRecord mcreator_19 = new mcreator_shapelessBlackRecord();
mcreator_shapelessWhiteRecord mcreator_20 = new mcreator_shapelessWhiteRecord();
mcreator_shapelessUVRecord mcreator_21 = new mcreator_shapelessUVRecord();
mcreator_shapelessGoldRecord mcreator_22 = new mcreator_shapelessGoldRecord();
mcreator_shapelessYellowRecord mcreator_23 = new mcreator_shapelessYellowRecord();
mcreator_shapelessMagentaRecord mcreator_24 = new mcreator_shapelessMagentaRecord();
mcreator_shapelessBrownRecord mcreator_25 = new mcreator_shapelessBrownRecord();
mcreator_shapelessPurpleRecord mcreator_26 = new mcreator_shapelessPurpleRecord();
mcreator_shapelessSilverRecord mcreator_27 = new mcreator_shapelessSilverRecord();
mcreator_shapelessBlueRecord mcreator_28 = new mcreator_shapelessBlueRecord();
mcreator_indigoRecord mcreator_29 = new mcreator_indigoRecord();
mcreator_shapelessIndigoRecord mcreator_30 = new mcreator_shapelessIndigoRecord();
mcreator_wreckedShipStory mcreator_31 = new mcreator_wreckedShipStory();
mcreator_wreckedShipDiary mcreator_32 = new mcreator_wreckedShipDiary();
mcreator_alienOre mcreator_33 = new mcreator_alienOre();
mcreator_alienIngot mcreator_34 = new mcreator_alienIngot();
mcreator_hacheOre mcreator_35 = new mcreator_hacheOre();
mcreator_hacheGem mcreator_36 = new mcreator_hacheGem();
mcreator_hacheTab mcreator_37 = new mcreator_hacheTab();
mcreator_wreckedShipBow mcreator_38 = new mcreator_wreckedShipBow();
mcreator_genSeaWeedsdeepOcean mcreator_39 = new mcreator_genSeaWeedsdeepOcean();
mcreator_alienChip mcreator_40 = new mcreator_alienChip();
mcreator_autoSeederGUI mcreator_41 = new mcreator_autoSeederGUI();
mcreator_commandBlockRecipe mcreator_42 = new mcreator_commandBlockRecipe();
mcreator_secretRecord mcreator_43 = new mcreator_secretRecord();
mcreator_hacheArmor mcreator_44 = new mcreator_hacheArmor();
mcreator_compressedEndStone mcreator_45 = new mcreator_compressedEndStone();
mcreator_hachePickaxe mcreator_46 = new mcreator_hachePickaxe();
mcreator_hacheSword mcreator_47 = new mcreator_hacheSword();
mcreator_hacheAxe mcreator_48 = new mcreator_hacheAxe();
mcreator_hacheShovel mcreator_49 = new mcreator_hacheShovel();
mcreator_hacheHoe mcreator_50 = new mcreator_hacheHoe();
mcreator_hacheipe399 mcreator_51 = new mcreator_hacheipe399();
mcreator_chuhoPoopOre mcreator_52 = new mcreator_chuhoPoopOre();
mcreator_chuchoPoopRaw mcreator_53 = new mcreator_chuchoPoopRaw();
mcreator_chuchoPoopBlock mcreator_54 = new mcreator_chuchoPoopBlock();
mcreator_hacheOreBlock mcreator_55 = new mcreator_hacheOreBlock();
mcreator_aleinOreBlock mcreator_56 = new mcreator_aleinOreBlock();
mcreator_hacheHoeAlt mcreator_57 = new mcreator_hacheHoeAlt();
mcreator_hacheAxeAlt mcreator_58 = new mcreator_hacheAxeAlt();
mcreator_machinePurifier mcreator_59 = new mcreator_machinePurifier();
mcreator_barrierRecipe mcreator_60 = new mcreator_barrierRecipe();
mcreator_compressedObsidian mcreator_61 = new mcreator_compressedObsidian();
mcreator_integralStone mcreator_62 = new mcreator_integralStone();
mcreator_archAlienTech mcreator_63 = new mcreator_archAlienTech();
mcreator_purifierGUI mcreator_64 = new mcreator_purifierGUI();
mcreator_interspaceTransmitter mcreator_65 = new mcreator_interspaceTransmitter();
mcreator_thatPlanet mcreator_66 = new mcreator_thatPlanet();
mcreator_purifiedChuchoPoop mcreator_67 = new mcreator_purifiedChuchoPoop();
mcreator_defqonOneSpeaker mcreator_68 = new mcreator_defqonOneSpeaker();
mcreator_chuchoTNT mcreator_69 = new mcreator_chuchoTNT();
mcreator_thatPlanetGround mcreator_70 = new mcreator_thatPlanetGround();
mcreator_thatPlanetBiomeBase mcreator_71 = new mcreator_thatPlanetBiomeBase();
mcreator_alienofThatPlanet mcreator_72 = new mcreator_alienofThatPlanet();
mcreator_alienBrickGreen mcreator_73 = new mcreator_alienBrickGreen();
mcreator_alienBrickOrange mcreator_74 = new mcreator_alienBrickOrange();


@Override
public int getBurnTime(ItemStack fuel) {
if(mcreator_0.addFuel(fuel)!=0) return mcreator_0.addFuel(fuel);
if(mcreator_1.addFuel(fuel)!=0) return mcreator_1.addFuel(fuel);
if(mcreator_2.addFuel(fuel)!=0) return mcreator_2.addFuel(fuel);
if(mcreator_3.addFuel(fuel)!=0) return mcreator_3.addFuel(fuel);
if(mcreator_4.addFuel(fuel)!=0) return mcreator_4.addFuel(fuel);
if(mcreator_5.addFuel(fuel)!=0) return mcreator_5.addFuel(fuel);
if(mcreator_6.addFuel(fuel)!=0) return mcreator_6.addFuel(fuel);
if(mcreator_7.addFuel(fuel)!=0) return mcreator_7.addFuel(fuel);
if(mcreator_8.addFuel(fuel)!=0) return mcreator_8.addFuel(fuel);
if(mcreator_9.addFuel(fuel)!=0) return mcreator_9.addFuel(fuel);
if(mcreator_10.addFuel(fuel)!=0) return mcreator_10.addFuel(fuel);
if(mcreator_11.addFuel(fuel)!=0) return mcreator_11.addFuel(fuel);
if(mcreator_12.addFuel(fuel)!=0) return mcreator_12.addFuel(fuel);
if(mcreator_13.addFuel(fuel)!=0) return mcreator_13.addFuel(fuel);
if(mcreator_14.addFuel(fuel)!=0) return mcreator_14.addFuel(fuel);
if(mcreator_15.addFuel(fuel)!=0) return mcreator_15.addFuel(fuel);
if(mcreator_16.addFuel(fuel)!=0) return mcreator_16.addFuel(fuel);
if(mcreator_17.addFuel(fuel)!=0) return mcreator_17.addFuel(fuel);
if(mcreator_18.addFuel(fuel)!=0) return mcreator_18.addFuel(fuel);
if(mcreator_19.addFuel(fuel)!=0) return mcreator_19.addFuel(fuel);
if(mcreator_20.addFuel(fuel)!=0) return mcreator_20.addFuel(fuel);
if(mcreator_21.addFuel(fuel)!=0) return mcreator_21.addFuel(fuel);
if(mcreator_22.addFuel(fuel)!=0) return mcreator_22.addFuel(fuel);
if(mcreator_23.addFuel(fuel)!=0) return mcreator_23.addFuel(fuel);
if(mcreator_24.addFuel(fuel)!=0) return mcreator_24.addFuel(fuel);
if(mcreator_25.addFuel(fuel)!=0) return mcreator_25.addFuel(fuel);
if(mcreator_26.addFuel(fuel)!=0) return mcreator_26.addFuel(fuel);
if(mcreator_27.addFuel(fuel)!=0) return mcreator_27.addFuel(fuel);
if(mcreator_28.addFuel(fuel)!=0) return mcreator_28.addFuel(fuel);
if(mcreator_29.addFuel(fuel)!=0) return mcreator_29.addFuel(fuel);
if(mcreator_30.addFuel(fuel)!=0) return mcreator_30.addFuel(fuel);
if(mcreator_31.addFuel(fuel)!=0) return mcreator_31.addFuel(fuel);
if(mcreator_32.addFuel(fuel)!=0) return mcreator_32.addFuel(fuel);
if(mcreator_33.addFuel(fuel)!=0) return mcreator_33.addFuel(fuel);
if(mcreator_34.addFuel(fuel)!=0) return mcreator_34.addFuel(fuel);
if(mcreator_35.addFuel(fuel)!=0) return mcreator_35.addFuel(fuel);
if(mcreator_36.addFuel(fuel)!=0) return mcreator_36.addFuel(fuel);
if(mcreator_37.addFuel(fuel)!=0) return mcreator_37.addFuel(fuel);
if(mcreator_38.addFuel(fuel)!=0) return mcreator_38.addFuel(fuel);
if(mcreator_39.addFuel(fuel)!=0) return mcreator_39.addFuel(fuel);
if(mcreator_40.addFuel(fuel)!=0) return mcreator_40.addFuel(fuel);
if(mcreator_41.addFuel(fuel)!=0) return mcreator_41.addFuel(fuel);
if(mcreator_42.addFuel(fuel)!=0) return mcreator_42.addFuel(fuel);
if(mcreator_43.addFuel(fuel)!=0) return mcreator_43.addFuel(fuel);
if(mcreator_44.addFuel(fuel)!=0) return mcreator_44.addFuel(fuel);
if(mcreator_45.addFuel(fuel)!=0) return mcreator_45.addFuel(fuel);
if(mcreator_46.addFuel(fuel)!=0) return mcreator_46.addFuel(fuel);
if(mcreator_47.addFuel(fuel)!=0) return mcreator_47.addFuel(fuel);
if(mcreator_48.addFuel(fuel)!=0) return mcreator_48.addFuel(fuel);
if(mcreator_49.addFuel(fuel)!=0) return mcreator_49.addFuel(fuel);
if(mcreator_50.addFuel(fuel)!=0) return mcreator_50.addFuel(fuel);
if(mcreator_51.addFuel(fuel)!=0) return mcreator_51.addFuel(fuel);
if(mcreator_52.addFuel(fuel)!=0) return mcreator_52.addFuel(fuel);
if(mcreator_53.addFuel(fuel)!=0) return mcreator_53.addFuel(fuel);
if(mcreator_54.addFuel(fuel)!=0) return mcreator_54.addFuel(fuel);
if(mcreator_55.addFuel(fuel)!=0) return mcreator_55.addFuel(fuel);
if(mcreator_56.addFuel(fuel)!=0) return mcreator_56.addFuel(fuel);
if(mcreator_57.addFuel(fuel)!=0) return mcreator_57.addFuel(fuel);
if(mcreator_58.addFuel(fuel)!=0) return mcreator_58.addFuel(fuel);
if(mcreator_59.addFuel(fuel)!=0) return mcreator_59.addFuel(fuel);
if(mcreator_60.addFuel(fuel)!=0) return mcreator_60.addFuel(fuel);
if(mcreator_61.addFuel(fuel)!=0) return mcreator_61.addFuel(fuel);
if(mcreator_62.addFuel(fuel)!=0) return mcreator_62.addFuel(fuel);
if(mcreator_63.addFuel(fuel)!=0) return mcreator_63.addFuel(fuel);
if(mcreator_64.addFuel(fuel)!=0) return mcreator_64.addFuel(fuel);
if(mcreator_65.addFuel(fuel)!=0) return mcreator_65.addFuel(fuel);
if(mcreator_66.addFuel(fuel)!=0) return mcreator_66.addFuel(fuel);
if(mcreator_67.addFuel(fuel)!=0) return mcreator_67.addFuel(fuel);
if(mcreator_68.addFuel(fuel)!=0) return mcreator_68.addFuel(fuel);
if(mcreator_69.addFuel(fuel)!=0) return mcreator_69.addFuel(fuel);
if(mcreator_70.addFuel(fuel)!=0) return mcreator_70.addFuel(fuel);
if(mcreator_71.addFuel(fuel)!=0) return mcreator_71.addFuel(fuel);
if(mcreator_72.addFuel(fuel)!=0) return mcreator_72.addFuel(fuel);
if(mcreator_73.addFuel(fuel)!=0) return mcreator_73.addFuel(fuel);
if(mcreator_74.addFuel(fuel)!=0) return mcreator_74.addFuel(fuel);
return 0;
}

@Override
public void generate(Random random, int chunkX, int chunkZ, World world, IChunkProvider chunkGenerator, IChunkProvider chunkProvider) {

chunkX = chunkX * 16;
chunkZ = chunkZ * 16;
if(world.provider.getDimensionId()==-1)mcreator_0.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_0.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_1.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_1.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_2.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_2.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_3.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_3.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_4.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_4.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_5.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_5.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_6.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_6.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_7.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_7.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_8.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_8.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_9.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_9.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_10.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_10.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_11.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_11.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_12.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_12.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_13.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_13.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_14.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_14.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_15.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_15.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_16.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_16.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_17.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_17.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_18.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_18.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_19.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_19.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_20.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_20.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_21.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_21.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_22.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_22.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_23.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_23.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_24.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_24.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_25.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_25.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_26.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_26.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_27.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_27.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_28.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_28.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_29.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_29.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_30.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_30.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_31.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_31.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_32.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_32.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_33.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_33.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_34.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_34.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_35.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_35.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_36.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_36.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_37.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_37.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_38.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_38.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_39.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_39.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_40.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_40.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_41.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_41.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_42.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_42.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_43.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_43.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_44.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_44.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_45.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_45.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_46.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_46.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_47.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_47.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_48.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_48.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_49.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_49.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_50.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_50.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_51.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_51.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_52.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_52.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_53.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_53.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_54.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_54.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_55.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_55.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_56.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_56.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_57.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_57.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_58.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_58.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_59.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_59.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_60.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_60.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_61.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_61.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_62.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_62.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_63.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_63.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_64.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_64.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_65.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_65.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_66.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_66.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_67.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_67.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_68.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_68.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_69.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_69.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_70.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_70.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_71.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_71.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_72.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_72.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_73.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_73.generateSurface(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==-1)mcreator_74.generateNether(world, random, chunkX, chunkZ);
if(world.provider.getDimensionId()==0)mcreator_74.generateSurface(world, random, chunkX, chunkZ);


}
@EventHandler
public void load(FMLInitializationEvent event) {

GameRegistry.registerFuelHandler(this);
GameRegistry.registerWorldGenerator(this, 1);
if(event.getSide() == Side.CLIENT){
OBJLoader.instance.addDomain("TestEnvironmentMod");
}
MinecraftForge.EVENT_BUS.register(new mcreator_GlobalEventsTestEnvironmentMod());
NetworkRegistry.INSTANCE.registerGuiHandler(this, new GuiHandler());
mcreator_0.load(event);
mcreator_1.load(event);
mcreator_2.load(event);
mcreator_3.load(event);
mcreator_4.load(event);
mcreator_5.load(event);
mcreator_6.load(event);
mcreator_7.load(event);
mcreator_8.load(event);
mcreator_9.load(event);
mcreator_10.load(event);
mcreator_11.load(event);
mcreator_12.load(event);
mcreator_13.load(event);
mcreator_14.load(event);
mcreator_15.load(event);
mcreator_16.load(event);
mcreator_17.load(event);
mcreator_18.load(event);
mcreator_19.load(event);
mcreator_20.load(event);
mcreator_21.load(event);
mcreator_22.load(event);
mcreator_23.load(event);
mcreator_24.load(event);
mcreator_25.load(event);
mcreator_26.load(event);
mcreator_27.load(event);
mcreator_28.load(event);
mcreator_29.load(event);
mcreator_30.load(event);
mcreator_31.load(event);
mcreator_32.load(event);
mcreator_33.load(event);
mcreator_34.load(event);
mcreator_35.load(event);
mcreator_36.load(event);
mcreator_37.load(event);
mcreator_38.load(event);
mcreator_39.load(event);
mcreator_40.load(event);
mcreator_41.load(event);
mcreator_42.load(event);
mcreator_43.load(event);
mcreator_44.load(event);
mcreator_45.load(event);
mcreator_46.load(event);
mcreator_47.load(event);
mcreator_48.load(event);
mcreator_49.load(event);
mcreator_50.load(event);
mcreator_51.load(event);
mcreator_52.load(event);
mcreator_53.load(event);
mcreator_54.load(event);
mcreator_55.load(event);
mcreator_56.load(event);
mcreator_57.load(event);
mcreator_58.load(event);
mcreator_59.load(event);
mcreator_60.load(event);
mcreator_61.load(event);
mcreator_62.load(event);
mcreator_63.load(event);
mcreator_64.load(event);
mcreator_65.load(event);
mcreator_66.load(event);
mcreator_67.load(event);
mcreator_68.load(event);
mcreator_69.load(event);
mcreator_70.load(event);
mcreator_71.load(event);
mcreator_72.load(event);
mcreator_73.load(event);
mcreator_74.load(event);


}
@EventHandler
public void serverLoad(FMLServerStartingEvent event){
mcreator_0.serverLoad(event);
mcreator_1.serverLoad(event);
mcreator_2.serverLoad(event);
mcreator_3.serverLoad(event);
mcreator_4.serverLoad(event);
mcreator_5.serverLoad(event);
mcreator_6.serverLoad(event);
mcreator_7.serverLoad(event);
mcreator_8.serverLoad(event);
mcreator_9.serverLoad(event);
mcreator_10.serverLoad(event);
mcreator_11.serverLoad(event);
mcreator_12.serverLoad(event);
mcreator_13.serverLoad(event);
mcreator_14.serverLoad(event);
mcreator_15.serverLoad(event);
mcreator_16.serverLoad(event);
mcreator_17.serverLoad(event);
mcreator_18.serverLoad(event);
mcreator_19.serverLoad(event);
mcreator_20.serverLoad(event);
mcreator_21.serverLoad(event);
mcreator_22.serverLoad(event);
mcreator_23.serverLoad(event);
mcreator_24.serverLoad(event);
mcreator_25.serverLoad(event);
mcreator_26.serverLoad(event);
mcreator_27.serverLoad(event);
mcreator_28.serverLoad(event);
mcreator_29.serverLoad(event);
mcreator_30.serverLoad(event);
mcreator_31.serverLoad(event);
mcreator_32.serverLoad(event);
mcreator_33.serverLoad(event);
mcreator_34.serverLoad(event);
mcreator_35.serverLoad(event);
mcreator_36.serverLoad(event);
mcreator_37.serverLoad(event);
mcreator_38.serverLoad(event);
mcreator_39.serverLoad(event);
mcreator_40.serverLoad(event);
mcreator_41.serverLoad(event);
mcreator_42.serverLoad(event);
mcreator_43.serverLoad(event);
mcreator_44.serverLoad(event);
mcreator_45.serverLoad(event);
mcreator_46.serverLoad(event);
mcreator_47.serverLoad(event);
mcreator_48.serverLoad(event);
mcreator_49.serverLoad(event);
mcreator_50.serverLoad(event);
mcreator_51.serverLoad(event);
mcreator_52.serverLoad(event);
mcreator_53.serverLoad(event);
mcreator_54.serverLoad(event);
mcreator_55.serverLoad(event);
mcreator_56.serverLoad(event);
mcreator_57.serverLoad(event);
mcreator_58.serverLoad(event);
mcreator_59.serverLoad(event);
mcreator_60.serverLoad(event);
mcreator_61.serverLoad(event);
mcreator_62.serverLoad(event);
mcreator_63.serverLoad(event);
mcreator_64.serverLoad(event);
mcreator_65.serverLoad(event);
mcreator_66.serverLoad(event);
mcreator_67.serverLoad(event);
mcreator_68.serverLoad(event);
mcreator_69.serverLoad(event);
mcreator_70.serverLoad(event);
mcreator_71.serverLoad(event);
mcreator_72.serverLoad(event);
mcreator_73.serverLoad(event);
mcreator_74.serverLoad(event);
}
@EventHandler
public void preInit(FMLPreInitializationEvent event){
mcreator_0.instance = this.instance;
mcreator_1.instance = this.instance;
mcreator_2.instance = this.instance;
mcreator_3.instance = this.instance;
mcreator_4.instance = this.instance;
mcreator_5.instance = this.instance;
mcreator_6.instance = this.instance;
mcreator_7.instance = this.instance;
mcreator_8.instance = this.instance;
mcreator_9.instance = this.instance;
mcreator_10.instance = this.instance;
mcreator_11.instance = this.instance;
mcreator_12.instance = this.instance;
mcreator_13.instance = this.instance;
mcreator_14.instance = this.instance;
mcreator_15.instance = this.instance;
mcreator_16.instance = this.instance;
mcreator_17.instance = this.instance;
mcreator_18.instance = this.instance;
mcreator_19.instance = this.instance;
mcreator_20.instance = this.instance;
mcreator_21.instance = this.instance;
mcreator_22.instance = this.instance;
mcreator_23.instance = this.instance;
mcreator_24.instance = this.instance;
mcreator_25.instance = this.instance;
mcreator_26.instance = this.instance;
mcreator_27.instance = this.instance;
mcreator_28.instance = this.instance;
mcreator_29.instance = this.instance;
mcreator_30.instance = this.instance;
mcreator_31.instance = this.instance;
mcreator_32.instance = this.instance;
mcreator_33.instance = this.instance;
mcreator_34.instance = this.instance;
mcreator_35.instance = this.instance;
mcreator_36.instance = this.instance;
mcreator_37.instance = this.instance;
mcreator_38.instance = this.instance;
mcreator_39.instance = this.instance;
mcreator_40.instance = this.instance;
mcreator_41.instance = this.instance;
mcreator_42.instance = this.instance;
mcreator_43.instance = this.instance;
mcreator_44.instance = this.instance;
mcreator_45.instance = this.instance;
mcreator_46.instance = this.instance;
mcreator_47.instance = this.instance;
mcreator_48.instance = this.instance;
mcreator_49.instance = this.instance;
mcreator_50.instance = this.instance;
mcreator_51.instance = this.instance;
mcreator_52.instance = this.instance;
mcreator_53.instance = this.instance;
mcreator_54.instance = this.instance;
mcreator_55.instance = this.instance;
mcreator_56.instance = this.instance;
mcreator_57.instance = this.instance;
mcreator_58.instance = this.instance;
mcreator_59.instance = this.instance;
mcreator_60.instance = this.instance;
mcreator_61.instance = this.instance;
mcreator_62.instance = this.instance;
mcreator_63.instance = this.instance;
mcreator_64.instance = this.instance;
mcreator_65.instance = this.instance;
mcreator_66.instance = this.instance;
mcreator_67.instance = this.instance;
mcreator_68.instance = this.instance;
mcreator_69.instance = this.instance;
mcreator_70.instance = this.instance;
mcreator_71.instance = this.instance;
mcreator_72.instance = this.instance;
mcreator_73.instance = this.instance;
mcreator_74.instance = this.instance;
mcreator_0.preInit(event);
mcreator_1.preInit(event);
mcreator_2.preInit(event);
mcreator_3.preInit(event);
mcreator_4.preInit(event);
mcreator_5.preInit(event);
mcreator_6.preInit(event);
mcreator_7.preInit(event);
mcreator_8.preInit(event);
mcreator_9.preInit(event);
mcreator_10.preInit(event);
mcreator_11.preInit(event);
mcreator_12.preInit(event);
mcreator_13.preInit(event);
mcreator_14.preInit(event);
mcreator_15.preInit(event);
mcreator_16.preInit(event);
mcreator_17.preInit(event);
mcreator_18.preInit(event);
mcreator_19.preInit(event);
mcreator_20.preInit(event);
mcreator_21.preInit(event);
mcreator_22.preInit(event);
mcreator_23.preInit(event);
mcreator_24.preInit(event);
mcreator_25.preInit(event);
mcreator_26.preInit(event);
mcreator_27.preInit(event);
mcreator_28.preInit(event);
mcreator_29.preInit(event);
mcreator_30.preInit(event);
mcreator_31.preInit(event);
mcreator_32.preInit(event);
mcreator_33.preInit(event);
mcreator_34.preInit(event);
mcreator_35.preInit(event);
mcreator_36.preInit(event);
mcreator_37.preInit(event);
mcreator_38.preInit(event);
mcreator_39.preInit(event);
mcreator_40.preInit(event);
mcreator_41.preInit(event);
mcreator_42.preInit(event);
mcreator_43.preInit(event);
mcreator_44.preInit(event);
mcreator_45.preInit(event);
mcreator_46.preInit(event);
mcreator_47.preInit(event);
mcreator_48.preInit(event);
mcreator_49.preInit(event);
mcreator_50.preInit(event);
mcreator_51.preInit(event);
mcreator_52.preInit(event);
mcreator_53.preInit(event);
mcreator_54.preInit(event);
mcreator_55.preInit(event);
mcreator_56.preInit(event);
mcreator_57.preInit(event);
mcreator_58.preInit(event);
mcreator_59.preInit(event);
mcreator_60.preInit(event);
mcreator_61.preInit(event);
mcreator_62.preInit(event);
mcreator_63.preInit(event);
mcreator_64.preInit(event);
mcreator_65.preInit(event);
mcreator_66.preInit(event);
mcreator_67.preInit(event);
mcreator_68.preInit(event);
mcreator_69.preInit(event);
mcreator_70.preInit(event);
mcreator_71.preInit(event);
mcreator_72.preInit(event);
mcreator_73.preInit(event);
mcreator_74.preInit(event);
proxy.registerRenderers(this);
}
public static class GuiHandler implements IGuiHandler {
@Override public Object getServerGuiElement(int id, EntityPlayer player, World world, int x, int y, int z) {
if(id == mcreator_wreckedShipStory.GUIID)return new mcreator_wreckedShipStory.GuiContainerMod(world, x, y, z, player);
if(id == mcreator_autoSeederGUI.GUIID)return new mcreator_autoSeederGUI.GuiContainerMod(world, x, y, z, player);
if(id == mcreator_purifierGUI.GUIID)return new mcreator_purifierGUI.GuiContainerMod(world, x, y, z, player);
return null;}
@Override public Object getClientGuiElement(int id, EntityPlayer player, World world, int x, int y, int z) {
if(id == mcreator_wreckedShipStory.GUIID)return new mcreator_wreckedShipStory.GuiWindow(world, x, y, z, player);
if(id == mcreator_autoSeederGUI.GUIID)return new mcreator_autoSeederGUI.GuiWindow(world, x, y, z, player);
if(id == mcreator_purifierGUI.GUIID)return new mcreator_purifierGUI.GuiWindow(world, x, y, z, player);
return null;}
}


}
